import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css'
import Script from "next/script";

import "./globals.css"
import MenuLateral from "./components/MenuLateral";
import MenuSuperior from "./components/MenuSuperior";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <MenuSuperior/>

        <div class="container-fluid">
          <div class="row">
            <div className="col-2">

              <MenuLateral/>

            </div>

            <div className="col-10">

              {children}
              
            </div>
          </div>
        </div>


        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" />
      </body>
    </html>
  );
}
